### ISSUE TITLE
Important messages

### ISSUE THREAD

**Issue by gh0c** [standaniels/flash#2]
In your [messages view](https://github.com/standaniels/flash/blob/master/src/views/messages.blade.php), button to close alert should appear when message **is** _important_, right (to close it manually)?

So instead of `@if(!$message->has('important'))` it should say `@if($message->has('important'))`

BTW thanks for this extended version of Jeff's package, multiple flash messages are definitely more helpful

**Comment by standaniels** [comment]
Thank you for your message. You're right, it should show a close button for important messages. Could you make a PR please?
